name: Generate Snake Animation

on:
  schedule: 
    - cron: "0 0 * * *"  # runs every day at midnight
  workflow_dispatch:     # lets you run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: tdineth
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push Snake Animation to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
